name: shop_app
description: A Shop Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2021090601

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0 # State management

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  uuid: 3.0.4 # Random ID generator
  intl: ^0.17.0 # Date formatter
  http: ^0.13.3 # Network requests
  get_it: ^7.2.0 # Accessing objects over all the app
  f_logs: ^2.0.0 # Logging
  enum_to_string: ^2.0.1 # Enum conversion to string
  connectivity_plus: ^1.0.7 # Internet connectivity
  flutter_spinkit: ^5.0.0 # Loaders
  flutter_native_splash: ^1.2.1 # Native splash screen generator
  flutter_launcher_icons: ^0.9.1 # Launcher icon generator
  shared_preferences: ^2.0.7 # Persistent storage
  font_awesome_flutter: ^9.1.0 # Font awesome icons
  package_info_plus: ^1.0.6 # Application package details
  page_transition: ^2.0.2 # Page transitions

# flutter pub run flutter_native_splash:create
# flutter pub run flutter_native_splash:remove
flutter_native_splash:
  fullscreen: true
  image: assets/images/ic_splash.png
  color: '#FFFFFF'
  android: true
  ios: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: 'assets/images/ic_launcher.png'
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf